### PR TITLE
Use metaserialport to handle serialport@1 vs serialport@2

### PR DESCRIPTION
**Pull request by aredridel**
(this is based on v0.6.0, and so will conflict with current master, which solves the same problem differently)

### CODE REVIEW

**Comment by rwaldron** [comment]
Node 4 is currently supported on master.

**Comment by rwaldron** [comment]
> which solves the same problem differently)

Does this install on 0.10.x, 0.12.x without errors?

**Comment by aredridel** [comment]
It should! I'd love another set of eyes on it to test though!

**Comment by rwaldron** [comment]
@aredridel ok, here's the full run output: 

(starting on node v4.2.1)
```
rwaldron at nova in ~/robotz/firmata-install-test
$ node -v
v4.2.1
rwaldron at nova in ~/robotz/firmata-install-test
$ npm install git://github.com/aredridel/firmata.git#metaserialport
-
> serialport@2.0.1 install /Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-2/node_modules/serialport
> node-pre-gyp install --fallback-to-build

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
../src/serialport_unix.cpp:695:20: warning: comparison of array 'device.locationId' not
      equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.locationId != NULL) {
            ~~~~~~~^~~~~~~~~~    ~~~~
../src/serialport_unix.cpp:698:20: warning: comparison of array 'device.vendorId' not
      equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.vendorId != NULL) {
            ~~~~~~~^~~~~~~~    ~~~~
../src/serialport_unix.cpp:701:20: warning: comparison of array 'device.productId' not
      equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.productId != NULL) {
            ~~~~~~~^~~~~~~~~    ~~~~
../src/serialport_unix.cpp:704:20: warning: comparison of array 'device.manufacturer' not
      equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.manufacturer != NULL) {
            ~~~~~~~^~~~~~~~~~~~    ~~~~
../src/serialport_unix.cpp:707:20: warning: comparison of array 'device.serialNumber' not
      equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.serialNumber != NULL) {
            ~~~~~~~^~~~~~~~~~~~    ~~~~
5 warnings generated.
  CXX(target) Release/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Release/serialport.node
  SOLINK_MODULE(target) Release/serialport.node: Finished
  COPY /Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-2/node_modules/serialport/build/serialport/v2.0.1/Release/node-v46-darwin-x64/serialport.node
  TOUCH Release/obj.target/action_after_build.stamp

> serialport@1.7.4 install /Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-1/node_modules/serialport
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/serialport/src/serialport.o
In file included from ../src/serialport.cpp:3:
In file included from ../src/serialport.h:5:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/rwaldron/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: candidate function
      not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to
      'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/rwaldron/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: candidate function
      not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/rwaldron/.node-gyp/4.2.1/include/node/node_buffer.h:28:40: note: candidate function
      not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/rwaldron/.node-gyp/4.2.1/include/node/node_buffer.h:36:40: note: candidate function
      not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/serialport.cpp:3:
In file included from ../src/serialport.h:5:
../node_modules/nan/nan.h:676:12: error: no viable conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/rwaldron/.node-gyp/4.2.1/include/node/v8.h:210:7: note: candidate constructor (the
      implicit copy constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/rwaldron/.node-gyp/4.2.1/include/node/v8.h:210:7: note: candidate constructor (the
      implicit move constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/rwaldron/.node-gyp/4.2.1/include/node/v8.h:214:13: note: candidate template
      ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/rwaldron/.node-gyp/4.2.1/include/node/v8.h:326:13: note: candidate template
      ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/serialport.cpp:3:
In file included from ../src/serialport.h:5:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/serialport.cpp:3:
In file included from ../src/serialport.h:5:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/rwaldron/.node-gyp/4.2.1/include/node/node.h:42:
/Users/rwaldron/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to
      'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/rwaldron/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/serialport.cpp:3:
In file included from ../src/serialport.h:5:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/rwaldron/.node-gyp/4.2.1/include/node/node.h:42:
/Users/rwaldron/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to
      'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/rwaldron/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/serialport.cpp:3:
In file included from ../src/serialport.h:5:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/rwaldron/.node-gyp/4.2.1/include/node/node.h:42:
/Users/rwaldron/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to
      'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/rwaldron/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/serialport.cpp:3:
In file included from ../src/serialport.h:5:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/rwaldron/.node-gyp/4.2.1/include/node/node.h:42:
/Users/rwaldron/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to
      'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/rwaldron/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/serialport/src/serialport.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-1/node_modules/serialport/build/serialport/v1.7.4/Release/node-v46-darwin-x64/serialport.node" "--module_name=serialport" "--module_path=/Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-1/node_modules/serialport/build/serialport/v1.7.4/Release/node-v46-darwin-x64"
gyp ERR! cwd /Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-1/node_modules/serialport
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-1/node_modules/serialport/build/serialport/v1.7.4/Release/node-v46-darwin-x64/serialport.node --module_name=serialport --module_path=/Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-1/node_modules/serialport/build/serialport/v1.7.4/Release/node-v46-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-1/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.0.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-1/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-1/node_modules/serialport
node-pre-gyp ERR! node -v v4.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-1/node_modules/serialport/build/serialport/v1.7.4/Release/node-v46-darwin-x64/serialport.node --module_name=serialport --module_path=/Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-1/node_modules/serialport/build/serialport/v1.7.4/Release/node-v46-darwin-x64' (1)
npm WARN optional dep failed, continuing serialport-1@1.0.1
firmata@0.6.0 node_modules/firmata
├── object-assign@1.0.0
├── browser-serialport@2.0.3
├── grunt-cli@0.1.13 (resolve@0.3.1, nopt@1.0.10, findup-sync@0.1.3)
├── es6-map@0.1.2 (d@0.1.1, es6-symbol@3.0.0, event-emitter@0.3.4, es6-iterator@2.0.0, es6-set@0.1.2, es5-ext@0.10.8)
└── metaserialport@1.0.0 (serialport-2@1.0.1)
```

(Then, switched to node v0.12.4)
```
rwaldron at nova in ~/robotz/firmata-install-test
$ nvm use 0.12.4
Now using node v0.12.4
rwaldron at nova in ~/robotz/firmata-install-test
$ node -v
v0.12.4
rwaldron at nova in ~/robotz/firmata-install-test
$ npm install git://github.com/aredridel/firmata.git#metaserialport
|
> serialport@2.0.1 install /Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-2/node_modules/serialport
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
../src/serialport_unix.cpp:695:20: warning: comparison of array 'device.locationId' not
      equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.locationId != NULL) {
            ~~~~~~~^~~~~~~~~~    ~~~~
../src/serialport_unix.cpp:698:20: warning: comparison of array 'device.vendorId' not
      equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.vendorId != NULL) {
            ~~~~~~~^~~~~~~~    ~~~~
../src/serialport_unix.cpp:701:20: warning: comparison of array 'device.productId' not
      equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.productId != NULL) {
            ~~~~~~~^~~~~~~~~    ~~~~
../src/serialport_unix.cpp:704:20: warning: comparison of array 'device.manufacturer' not
      equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.manufacturer != NULL) {
            ~~~~~~~^~~~~~~~~~~~    ~~~~
../src/serialport_unix.cpp:707:20: warning: comparison of array 'device.serialNumber' not
      equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.serialNumber != NULL) {
            ~~~~~~~^~~~~~~~~~~~    ~~~~
5 warnings generated.
  CXX(target) Release/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Release/serialport.node
  SOLINK_MODULE(target) Release/serialport.node: Finished
  COPY /Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-2/node_modules/serialport/build/serialport/v2.0.1/Release/node-v14-darwin-x64/serialport.node
  TOUCH Release/obj.target/action_after_build.stamp

> serialport@1.7.4 install /Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-1/node_modules/serialport
> node-pre-gyp install --fallback-to-build

[serialport] Success: "/Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/metaserialport/node_modules/serialport-1/node_modules/serialport/build/serialport/v1.7.4/Release/node-v14-darwin-x64/serialport.node" is installed via remote
firmata@0.6.0 node_modules/firmata
├── object-assign@1.0.0
├── browser-serialport@2.0.3
├── grunt-cli@0.1.13 (resolve@0.3.1, nopt@1.0.10, findup-sync@0.1.3)
├── es6-map@0.1.2 (d@0.1.1, es6-symbol@3.0.0, event-emitter@0.3.4, es6-iterator@2.0.0, es6-set@0.1.2, es5-ext@0.10.8)
└── metaserialport@1.0.0 (serialport-2@1.0.1, serialport-1@1.0.1)
```

Since npm will attempt to install both versions, one of them is always going to fail. Here's the same output using the postinstall script on master: 

```
rwaldron at nova in ~/robotz/firmata-install-test
$ node -v
v4.2.1
rwaldron at nova in ~/robotz/firmata-install-test
$ npm install git://github.com/jgautier/firmata.git
-
> firmata@0.7.1-pre-2 postinstall /Users/rwaldron/robotz/firmata-install-test/node_modules/firmata
> node scripts/postinstall


> serialport@2.0.1 install /Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/serialport
> node-pre-gyp install --fallback-to-build


  CXX(target) Release/obj.target/serialport/src/serialport.o

  CXX(target) Release/obj.target/serialport/src/serialport_unix.o

  CXX(target) Release/obj.target/serialport/src/serialport_poller.o

  SOLINK_MODULE(target) Release/serialport.node

  SOLINK_MODULE(target) Release/serialport.node: Finished

  COPY /Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/serialport/build/serialport/v2.0.1/Release/node-v46-darwin-x64/serialport.node

  TOUCH Release/obj.target/action_after_build.stamp

serialport@2.0.1 node_modules/serialport
├── bindings@1.2.1
├── async@0.9.0
├── sf@0.1.7
├── debug@2.2.0 (ms@0.7.1)
├── nan@2.0.9
└── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)

firmata@0.7.1-pre-2 node_modules/firmata
├── browser-serialport@2.0.3
├── semver@5.0.3
└── es6-shim@0.33.6
rwaldron at nova in ~/robotz/firmata-install-test
$ rm -r node_modules/
rwaldron at nova in ~/robotz/firmata-install-test
$ nvm use 0.12.4
Now using node v0.12.4
rwaldron at nova in ~/robotz/firmata-install-test
$ node -v
v0.12.4
rwaldron at nova in ~/robotz/firmata-install-test
$ npm install git://github.com/jgautier/firmata.git
-
> firmata@0.7.1-pre-2 postinstall /Users/rwaldron/robotz/firmata-install-test/node_modules/firmata
> node scripts/postinstall


> serialport@1.7.4 install /Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/serialport
> node-pre-gyp install --fallback-to-build


[serialport] Success: "/Users/rwaldron/robotz/firmata-install-test/node_modules/firmata/node_modules/serialport/build/serialport/v1.7.4/Release/node-v14-darwin-x64/serialport.node" is installed via remote

serialport@1.7.4 node_modules/serialport
├── bindings@1.2.1
├── sf@0.1.7
├── async@0.9.0
├── nan@1.8.4
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
└── debug@2.2.0 (ms@0.7.1)

firmata@0.7.1-pre-2 node_modules/firmata
├── browser-serialport@2.0.3
├── semver@5.0.3
└── es6-shim@0.33.6
```

**Comment by aredridel** [comment]
Yup. It works by functionally testing, rather than mapping versions.

The ergonomics of the scary error for an optional dependency are definitely a bit quirky -- something I'd love to see npm improve, but is hard to get right.

**Comment by rwaldron** [comment]
Sorted out in 0.7.x releases—thanks again for helping with this :)

**Comment by aredridel** [comment]
Indeed! Happy to see it work!

**Pull request closed without merging**
